In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'coin_USDCoin.csv')

In [3]:
df.head()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,USD Coin,USDC,2018-10-09 23:59:59,1.00833,1.00003,1.00427,1.00686,108803.0,0.0
1,2,USD Coin,USDC,2018-10-10 23:59:59,1.01908,1.00397,1.00494,1.00962,711783.0,0.0
2,3,USD Coin,USDC,2018-10-11 23:59:59,1.03123,1.00173,1.00994,1.00978,4177290.0,0.0
3,4,USD Coin,USDC,2018-10-12 23:59:59,1.01871,1.00114,1.00861,1.01272,1322240.0,0.0
4,5,USD Coin,USDC,2018-10-13 23:59:59,1.02029,1.00355,1.01445,1.00743,698507.0,0.0

In [4]:
# format the specified columns

columns_to_format = ['High', 'Low', 'Open', 'Close', 'Volume', 'Marketcap']
df[columns_to_format] = df[columns_to_format].applymap(lambda x: f'{x:.2f}'.replace('.', ','))

# format date column to date

df['Date'] = pd.to_datetime(df['Date'])

df

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,USD Coin,USDC,2018-10-09 23:59:59,"1,01","1,00","1,00","1,01","108803,00","0,00"
1,2,USD Coin,USDC,2018-10-10 23:59:59,"1,02","1,00","1,00","1,01","711783,00","0,00"
2,3,USD Coin,USDC,2018-10-11 23:59:59,"1,03","1,00","1,01","1,01","4177290,00","0,00"
3,4,USD Coin,USDC,2018-10-12 23:59:59,"1,02","1,00","1,01","1,01","1322240,00","0,00"
4,5,USD Coin,USDC,2018-10-13 23:59:59,"1,02","1,00","1,01","1,01","698507,00","0,00"
...,...,...,...,...,...,...,...,...,...,...
997,998,USD Coin,USDC,2021-07-02 23:59:59,"1,00","1,00","1,00","1,00","1787895570,34","25397754841,34"
998,999,USD Coin,USDC,2021-07-03 23:59:59,"1,00","1,00","1,00","1,00","1491016820,84","25504372338,91"
999,1000,USD Coin,USDC,2021-07-04 23:59:59,"1,00","1,00","1,00","1,00","1578667344,18","25511718609,01"
1000,1001,USD Coin,USDC,2021-07-05 23:59:59,"1,00","1,00","1,00","1,00","1887495557,89","25547238479,82"
1001,1002,USD Coin,USDC,2021-07-06 23:59:59,"1,00","1,00","1,00","1,00","2312601909,64","25673216975,57"

In [5]:
# save df to csv

df.to_csv(r'usdcoin.csv', index=False)